### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'logits'

### ISSUE THREAD

**Issue by mayank31398** [Silin159/SeKnow#1]
```
Traceback (most recent call last):
  File "train_multiwoz.py", line 118, in <module>
    trainer.train()
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/train.py", line 447, in train
    self.run_evaluation(epoch)
  File "train_multiwoz.py", line 85, in run_evaluation
    self.run_test_evaluation(epoch)
  File "/u/mayank98/.conda/envs/SeKnow/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "train_multiwoz.py", line 48, in run_test_evaluation
    generate_predictions(self.prediction_pipeline, dataset, 'test-predictions.txt')
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/generate.py", line 81, in generate_predictions
    conversation = pipeline(conversation)
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/pipelines.py", line 247, in __call__
    original_belief_strs = self.predictor.predict_belief(contexts)
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/model.py", line 319, in predict_belief
    do_sample=False)
  File "/u/mayank98/.conda/envs/SeKnow/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/u/mayank98/.conda/envs/SeKnow/lib/python3.6/site-packages/transformers/generation_utils.py", line 503, in generate
    **model_kwargs,
  File "/u/mayank98/.conda/envs/SeKnow/lib/python3.6/site-packages/transformers/generation_utils.py", line 680, in greedy_search
    next_token_logits = outputs.logits[:, -1, :]
AttributeError: 'tuple' object has no attribute 'logits'
```

Using transformers-3.5.0
This happens with the requirements.txt in Seknow-PLM

**Comment by Silin159** [comment]
Probably this issue comes out because the transformer version is too old. Try to use transformers-4.6.0 or higher instead, we have updated the requirements.txt.

**Comment by Silin159** [comment]
If updating the version of transformers does not work, the second solution is probably: changing all the "outputs.logits" in generation_utils.py to "outputs[0]"

**Comment by mayank31398** [comment]
Updating transformers didn't work. However, I replaced by outputs[0] in generation_utils.py.
However, I am getting another error now.

```
Traceback (most recent call last):
  File "train_multiwoz.py", line 118, in <module>
    trainer.train()
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/train.py", line 447, in train
    self.run_evaluation(epoch)
  File "train_multiwoz.py", line 85, in run_evaluation
    self.run_test_evaluation(epoch)
  File "/u/mayank98/.conda/envs/SeKnow/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "train_multiwoz.py", line 48, in run_test_evaluation
    generate_predictions(self.prediction_pipeline, dataset, 'test-predictions.txt')
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/generate.py", line 81, in generate_predictions
    conversation = pipeline(conversation)
  File "/dccstor/mayankgpfs/scratch/SeKnow/SeKnow-PLM/scripts/pipelines.py", line 249, in __call__
    dbs_results_query = list(map(partial(self.database, return_results=True), beliefs))
TypeError: the first argument must be callable
```

This error looks is in the seknow code and not huggingface library.
Apparantly, there is a non-callable argument in the functors.partial method.

Thanks for the quick reply :)

**Comment by Silin159** [comment]
"self.database" here is loaded from Line53: "dataset.database = AutoDatabase.load(path)" in scripts/data/dataset.py
"AutoDatabase" is defined in scripts/utils.py, where "database" returned by load() is loaded as "Database" in database.py from the downloaded datasets/multiwoz-2.1/database.zip
The Database class in database.py from datasets/multiwoz-2.1/database.zip should have \_\_call\_\_ method, could you check if the self.database is correctly loaded?
We are also confirming that it works right, and we have updated the requirements.txt to include all our used packages.

**Comment by Silin159** [comment]
"self.database" works right on our server, where we use transformers 3.5.0 + torch 1.6.0 with CUDA 10.1 and Python 3.7.10
"outputs.logits" in transformers/generation_utils.py is changed to "outputs[0]"
